sonar.projectKey=authmicroservice
sonar.projectName=Auth Microservice
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.token=sqp_08a5bc5ff32266e100e0eb92ae18e197fc993e5c
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes