package com.hubsi.authmicroservice.controller;

import com.hubsi.authmicroservice.adapters.in.controller.AuthController;
import com.hubsi.authmicroservice.adapters.in.request.LoginRequest;
import com.hubsi.authmicroservice.adapters.in.request.RegisterRequest;
import com.hubsi.authmicroservice.adapters.out.response.AuthResponse;
import com.hubsi.authmicroservice.adapters.out.response.RegisterResponse;
import com.hubsi.authmicroservice.application.services.AuthService;
import com.hubsi.authmicroservice.application.services.UserService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

class AuthControllerTest {

    @Mock
    private UserService userService;

    @Mock
    private AuthService authService;

    @InjectMocks
    private AuthController authController;

    @BeforeEach
    void setUp() {
        MockitoAnnotations.openMocks(this);
    }

    @Test
    void testRegister() {
        // Arrange
        RegisterRequest request = new RegisterRequest("Teste nome", "Teste sobrenome" ,"test@example.com", "password123");
        RegisterResponse expectedResponse = new RegisterResponse(
                "Usuário cadastrado com sucesso!",
                "jwtToken",
                request.email(),
                request.nome(),
                request.sobrenome(),
                "USER",
                null // Assuming ID is generated by the service
        );
        when(userService.registerUser(request)).thenReturn(expectedResponse);

        // Act
        ResponseEntity<RegisterResponse> response = authController.register(request);

        // Assert
        assertEquals(ResponseEntity.ok(expectedResponse), response);
        verify(userService, times(1)).registerUser(request);
    }

    @Test
    void testLogin() {
        // Arrange
        LoginRequest request = new LoginRequest("test@example.com", "password123");
        AuthResponse expectedResponse = new AuthResponse("jwtToken", "Login realizado com sucesso!");
        when(authService.authenticateUser(request.email(), request.password())).thenReturn(expectedResponse);

        // Act
        ResponseEntity<AuthResponse> response = authController.login(request);

        // Assert
        assertEquals(ResponseEntity.ok(expectedResponse), response);
        verify(authService, times(1)).authenticateUser(request.email(), request.password());
    }

    @Test
    void testRegisterWithDuplicateEmail(){

        RegisterRequest request = new RegisterRequest("Teste nome", "Teste sobrenome" ,"test@example.com", "password123");
        when(userService.registerUser(request)).thenThrow(new IllegalArgumentException("Email já está em uso"));

        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            authController.register(request);
        });

        assertEquals("Email já está em uso", exception.getMessage());
        verify(userService, times(1)).registerUser(request);

    }
}