package com.hubsi.authmicroservice.controller;

import com.hubsi.authmicroservice.adapters.in.controller.UserController;
import com.hubsi.authmicroservice.adapters.in.request.RegisterRequest;
import com.hubsi.authmicroservice.adapters.out.response.RegisterResponse;
import com.hubsi.authmicroservice.application.usecases.UserUseCases;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.ResponseEntity;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UserControllerTest {

    @Mock
    private UserUseCases userUseCases;

    @InjectMocks
    private UserController userController;

    @Test
    void testRegister() {
        // Arrange
        RegisterRequest request = new RegisterRequest("Teste nome", "Teste sobrenome" ,"test@example.com", "password123");
        RegisterResponse expectedResponse = new RegisterResponse(
                "Usuário cadastrado com sucesso!",
                "jwtToken",
                request.email(),
                request.nome(),
                request.sobrenome(),
                "USER",
                null // Assuming ID is generated by the service
        );
        when(userUseCases.registerUser(request)).thenReturn(expectedResponse);

        // Act
        ResponseEntity<RegisterResponse> response = userController.register(request);

        // Assert
        assertEquals(ResponseEntity.ok(expectedResponse), response);
        verify(userUseCases, times(1)).registerUser(request);
    }

    @Test
    void testRegisterWithDuplicateEmail(){

        RegisterRequest request = new RegisterRequest("Teste nome", "Teste sobrenome" ,"test@example.com", "password123");
        when(userUseCases.registerUser(request)).thenThrow(new IllegalArgumentException("Email já está em uso"));

        // Act & Assert
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
            userController.register(request);
        });

        assertEquals("Email já está em uso", exception.getMessage());
        verify(userUseCases, times(1)).registerUser(request);

    }
}
